name: rent2park
description: A car parking application for United States Of America.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.12
  equatable: ^2.0.3
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  font_awesome_flutter: ^9.1.0
  expandable: ^5.0.1
  google_maps_flutter: ^2.2.1
  location: ^4.3.0
  percent_indicator: ^3.4.0
  async: ^2.6.1
  share:
  country_picker: ^2.0.8
  image_picker: ^0.8.4+2
  flutter_credit_card: ^3.0.0
  google_maps_webservice: 0.0.20-nullsafety.5
  flutter_google_places: ^0.3.0
  uuid: ^3.0.5
  map_launcher: ^2.1.1
  pull_to_refresh: ^2.0.0
  flutter_rating_bar:
  firebase_core: ^1.12.0
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.6
  fl_chart: ^0.40.0
  flutter_slidable: 0.6.0
  webview_flutter: ^3.0.0
  syncfusion_flutter_datepicker: ^19.3.44
  fluster: ^1.2.0
  flutter_svg:
  dots_indicator: ^2.0.0
  flutter_facebook_auth: ^4.4.1+1
  firebase_messaging: ^10.0.8
  firebase_analytics: ^8.3.3
  twilio_flutter: ^0.0.9
  pin_code_fields: ^7.3.0
  flutter_chat_bubble: ^2.0.0
  flutter_local_notifications: ^9.0.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  url_launcher: ^6.1.5
  app_tracking_transparency: ^2.0.2+1
  fluttertoast: ^8.0.9
  flutter_switch: ^0.3.2
  geocoder2: ^1.1.2
  time_picker_sheet: ^0.0.2+1
  syncfusion_flutter_charts: ^19.4.56
  flutter_share: ^2.0.0
  number_inc_dec: ^0.8.0
  google_maps_cluster_manager: ^3.0.0+1
  jiffy: ^5.0.0
  another_flushbar: ^1.10.29
  pretty_http_logger: ^0.2.1
  geolocator: ^9.0.2
  flutter_card_scanner_latest: ^1.0.5
  custom_marker: ^1.0.0
#  flutter_stripe: ^6.0.0


#  blinkcard_flutter: ^2.6.0
#  card_scanner:
#    git:
#      url: https://github.com/yauheniprakapenka/card_scanner.git
#      ref: 5fef7e1 # v0.3.1

#  card_scanner: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

  fonts:
    - family: Gilroy_Bold
      fonts:
        - asset: fonts/gilroy_bold.ttf
    - family: Gilroy_Regular
      fonts:
        - asset: fonts/gilroy_regular.ttf
    - family: Gilroy_Light
      fonts:
        - asset: fonts/gilroy_light.otf
    - family: Gilroy_Medium
      fonts:
        - asset: fonts/gilroy_medium.ttf
    - family: Gilroy_SemiBold
      fonts:
        - asset: fonts/gilroy-semi_bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
