import 'package:flutter/material.dart';

import '../../../util/app_strings.dart';
import '../../../util/constants.dart';


class TermsAndConditionScreen extends StatelessWidget {
  static const String route = 'terms_and_condition_screen_route';

  const TermsAndConditionScreen();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Text(AppText.TERMS_AND_CONDITIONS_PRIVACY_POLICY,
              style: TextStyle(color: Constants.COLOR_ON_PRIMARY, fontFamily: Constants.GILROY_BOLD, fontSize: 17)),
          centerTitle: true,
          leading: IconButton(
              onPressed: () => Navigator.pop(context), icon: const BackButtonIcon(), color: Constants.COLOR_ON_PRIMARY),
          backgroundColor: Constants.COLOR_PRIMARY),
      body: SingleChildScrollView(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Padding(
                padding: EdgeInsets.symmetric(horizontal: 15, vertical: 20),
                child: Text(AppText.TERMS_AND_CONDITION,
                    style: TextStyle(color: Constants.COLOR_ON_SURFACE, fontSize: 18, fontFamily: Constants.GILROY_BOLD))),
            const Padding(
                padding: EdgeInsets.symmetric(horizontal: 20),
                child: Text('''
Rent 2 Park Terms & Conditions
 
Rent 2 Park provides on an online platform which has the sole purpose of enabling vehicle owners (“Drivers") and parking space holders (“Hosts”) to connect, reserve and rent parking space from one another.
 
This set of Rent 2 Park Terms & Conditions (this “Terms & Conditions”) applies to any and all use of (1) the Rent 2 Park website at http://www.rent2park.com and all affiliated websites owned and operated solely by Rent 2 Park (collectively, the “Rent 2 Park Site”), (2) the parking reservation services made available by Rent 2 Park through the Rent 2 Park Site, any Rent 2 Park-branded application for your mobile or other device (each, a “Rent 2 Park Application”), and any other online properties of Rent 2 Park or third parties, as described in Part I below (the “Reservation Services”), and (3) any other services or features made available by Rent 2 Park through the Rent 2 Park Site or any Rent 2 Park Application. Together, the items in (1) through (3) are referred to herein as the “Services”.
 
In this Terms & Conditions, “Rent 2 Park” and "we" mean Rent 2 Park, INC., a Florida corporation, and/or “User” and “you” mean any user of the Services. This Terms & Conditions incorporates Rent 2 Park’s standard policies, procedures, and terms and conditions for use of the Services that are referenced by name or by links in this Terms & Conditions (collectively, the “Rent 2 Park Policies”).
 
By accessing or using the Services or clicking “accept” or “agree” to this Terms & Conditions, (1) you acknowledge that you have read, understand and agree to be bound by this Terms & Conditions, and (2) you represent and warrant that you are at least eighteen (18) years old and are not prohibited by law from accessing or using the Services. THIS TERMS & CONDITIONS CONTAINS, AMONG OTHER THINGS, LIABILITY AND INDEMNITY PROVISIONS AND AN ARBITRATION PROVISION CONTAINING A CLASS ACTION WAIVER.
 
Rent 2 Park may update or revise this Terms & Conditions (including any Rent 2 Park Policies) from time to time without any prior notice to User. You agree that you will review this Terms & Conditions periodically. You are free to decide whether or not to accept a modified version of this Terms & Conditions, but accepting this Terms & Conditions, as modified, is required for you to continue using the Services. [You may have to click “accept” or “agree” to show your acceptance of any modified version of this Terms & Conditions.] If you do not agree to the terms of this Terms & Conditions or any modified version of this Terms & Conditions, your sole recourse is to immediately terminate your use of the Services, in which case you will no longer have access to your Account (as defined below). Except as otherwise expressly stated by Rent 2 Park, any use of the Services (e.g., to use the Reservation Services) is subject to the version of this Terms & Conditions in effect at the time of use.
 
Key Definitions
 
“User”
Any individual who is in contact with the Services, whether registered or not. All Users are bound by these Terms and Conditions whether registered or not. 
 
“Registered User” 
Any individual who has contacted the Services, provided the required information and completed the steps necessary to create an account.  
 
“Host”
Any Registered User who has created and published a Listing in the Services whether the owner, renter, or employee of the owner of that property. By creating and publishing a Listing within the Services Hosts indicate and attest they own or have obtained the right to operate on and rent out the listed property.
“Driver”
Any Registered User who uses the Services to seek parking space, request to utilize parking space, or complete an exchange of funds with Pavement or a Host for use of property.
 
“Listing”
A property which has been input into the Services and offered by a Host for Drivers to utilize. 
 
“Reservation”
An agreement between a Host and Driver to utilize a Host's offered Listing for a period of time, and the period of time during which a User’s vehicle is physically present on another User’s property as authorized by the agreement between Host and Driver. 
 
“Reservation Services”
The Reservation Services are defined as all tools and features provided to Users for the purposes of searching for, browsing, comparing, requesting or reserving parking spaces listed by other Rent 2 Park users as well as those tools/features provided for the purposes of managing, facilitating, editing and carrying out reservations, including payment processing, coupon redemption, messaging between users, archiving and tracking of past reservations and reservation activity for the purposes of granting User statuses or conducting loyalty programs, rating and reviewing of other users and their provided spaces and publishing of these ratings and reviews for use by other users, favorite listings, managing of vehicles and payment methods. 
 
“Host Services”
The Host Services are defined as all tools and features provided to Users for the purposes of listing and offering property for rent to other Rent 2 Park Users for temporary vehicle parking. The Host Services includes all tools/features provided for the purposes of managing and editing listing details and listing availability as well as all tools/features provided for the purposes of managing, facilitating, editing and carrying out reservations including payment processing and payout/distribution of funds to hosts, messaging between users, archiving and tracking of past reservations and reservation requests, tracking of Host activity and Host performance for the purpose of granting Host statuses, rating of Drivers publishing of these ratings for use by other users, managing of payment methods. 
 
Part I - Driver Reservation Services
 
1. Space Reservation. Rent 2 Park provides the Reservation Services to Users for the sole purposes of providing User’s information on the location and apparent availability of parking and assisting them in securing parking at participating third-party parking locations, including but not limited to private driveways, private garages, and private lots. In response to a User’s online request for a reservation through the Rent 2 Park Site or a Rent 2 Park Application, User communicates directly with the applicable individual holding/operating said space (the Host of the Listing) regarding such reservation request. The availability of reservations is determined at the time of a User’s query and Rent 2 Park makes no representation or warranty (i) regarding the accuracy of any data (including, but not limited to, reservation availability data) received from any Host.  Each Host is an independent third party and is not under the control of Rent 2 Park.  Rent 2 Park is not a guarantor, agent, or otherwise affiliated with any Host. You acknowledge that each Host may have its own policies, terms, and conditions.  Once a reservation request is made by a User through the Rent 2 Park Site or any Rent 2 Park Application, the Host with such space will provide confirmation of the Reservation to such User either by pre-authorizing the Services to auto accept all reservation requests within specified hours and specified days, or by manual approval at the time of request. By using the Reservation Services, you agree to receive reservation confirmations by Rent 2 Park messaging after requesting a Reservation through the Reservation Services.  You may terminate your Registration at any time by email Rent 2 Park at hello@rent2park.com.
 
In furtherance of (and not in any limitation of) the above, you hereby acknowledge and agree that notwithstanding the assistance that the Reservation Services provide to you in locating and reserving parking, the ultimate decision to utilize the parking information provided by the Reservation Services and to park at any location remains yours and yours alone, and you hereby agree to assume any risk inherent in utilizing the Reservation Services and/or deciding to actually park at any location. For the avoidance of doubt, Rent 2 Park does not in any way provide parking services or any kind or operate any parking locations. FURTHER, RENT 2 PARK ASSUMES NO RESPONSIBILITY OR LIABILITY FOR 1) THE SAFETY OF ANY PERSON, PROPERTY, OR VEHICLE PARKED AT ANY LOCATION OR 2) THE ACTUAL AVAILABILITY OF PARKING AT ANY LOCATION.  USE OF, OR A RESERVATION THROUGH, ANY RENT 2 PARK APPLICATION WILL IN NO WAY BE CONSIDERED A WARRANTY, GUARANTEE, OR OTHER REPRESENTATION THAT A SPECIFIC PARKING SPACE IS AVAILABLE AT ANY LOCATION AT ANY GIVEN TIME. RENT 2 PARK DISCLAIMS ANY AND ALL LIABILITY FOR DAMAGES, DELAYS, OR OTHER CONSEQUENCES THAT MAY ARISE IF A PARKING SPACE IS UNAVAILABLE, OR IF A RENT 2 PARK APPLICATION OTHERWISE ERRORS OR MALFUNCTIONS.
 
2. Calculation of Parking Rates; Payment Authorization; Taxes. You acknowledge that Rent 2 Park does not determine parking rates with Hosts to facilitate the booking of Reservations. The parking rate displayed on the Rent 2 Park Site or Rent 2 Park Application is determined solely by the Host and Rent 2 Park’s fees are in direct relation the price set by the Host. You agree to pay in full the price displayed on the Services for the total reservation price, which includes the parking rate plus, where applicable, service fees, and taxes at the time of your reservation request. 
 
All Reservations and other transactions consummated through the Rent 2 Park Site or a Rent 2 Park Application will be turned over to the relevant Host, and thereafter, a User may be required to enter into a separate agreement with that relevant Host. You acknowledge and confirm that you are authorized and permitted to use any credit card that you register on the Rent 2 Park Site or a Rent 2 Park Application. When you fund a transaction, you agree that Rent 2 Park is not in any way responsible or liable for the transaction. You acknowledge that Rent 2 Park does not collect taxes for remittance to applicable taxing authorities. The Hosts are solely responsible for remitting applicable taxes to the applicable taxing jurisdictions. 
 
3. Prices. The price of a parking reservation will be determined by the Host with the legal right to reserve said private location. Prices at each private location may change from time to time and at any time, but any such changes will not affect bookings already accepted by a Rent 2 Park Application.  Despite Rent 2 Park’s best efforts, some of the parking listed on the Services may be incorrectly priced. Rent 2 Park is under no obligation to fulfill a Reservation, even after you have been sent confirmation of your Reservation.  We do not guarantee that pricing for Reservations will be the best available at the time of reservation or reservation request.
 
4. Privacy Policy.  Rent 2 Park is committed to helping you safeguard your privacy online. Each User must review our Rent 2 Park Privacy Policy for details about how we collect and use information about the use of Rent 2 Park’s Services.  The Rent 2 Park Privacy Policy is expressly incorporated herein by reference.
 
5. Usage Guidelines. User agrees to use the Reservation Services only to book Reservations for User’s own use. Resale or attempted resale of Reservations is grounds for, among other things, cancellation of your Reservations and termination of your access to the Services. Rent 2 Park expressly reserves all its rights and remedies under applicable state and federal laws. Rent 2 Park reserves the right, in its sole discretion, to refuse service, terminate User accounts, remove or edit content, or cancel Reservations. User also agrees not to contact or attempt to contact Hosts by means other than the Services with intent to conduct a rental transaction for a property listed with the Services. You also agree not to use the Services to solicit or offer other user’s goods or services of any kind beyond reserving and renting parking spaces. 
 
6. Cancellations and Violations. By requesting a Reservation, you are agreeing to pay the rate published at that time for the requested period. If you later choose to cancel the Reservation, you agree to be subject to the Rent 2 Park Cancellation Policy which is subject to change without notice. You may also receive penalties for failure to remove your vehicle from a Host’s property by the end of the reservation period. Penalties for cancellation or failure to vacate a property at the agreed upon time may include but are not limited to, cash fines to be paid immediately, account suspensions, and negative reviews posted publicly on the Services in association with your account, which will inform and warn other Users of your cancellation or failure to vacate at the agreed upon time. By registering your payment information with the Services, you agree to allow Rent 2 Park to automatically charge in accordance with these policies. The fees and fines charged may vary.  The Rent 2 Park Cancellation Policy is expressly incorporated herein by reference.
 
7. Damage to Person or Property. By consenting to this Terms & Conditions you acknowledge that when you enter into a rental agreement with a Host you are choosing to enter the property offered by the Host for parking at your own discretion. By agreeing to these terms, you acknowledge that Rent 2 Park is not the owner or operator of any property available for rent via the Services and is not responsible for any damage or loss to property or person that may occur while you are on the Host’s property or engaged in a Reservation with the Host. All parking transactions are entered into at your own risk. We cannot and do not guarantee in any way the security of your vehicle or its contents. It is your responsibility to ensure that your vehicle is properly secured. If your vehicle is damaged while on a Host’s property, you agree to first attempt to resolve the matter with the Host. If the matter cannot be resolved through direct contact with the Host, you may contact Rent 2 Park customer service to record your case so that we can assess the situation and offer recourse where Rent 2 Park, in its sole discretion, deems such necessary. If your vehicle is stolen, contact the police and your insurance provider immediately. Rent 2 Park does not provide any insurance coverage to a User at any time. Certain Hosts may provide services in addition to parking, including but not limited to valet. These services may require you as a Guest to relinquish your keys to the Host. By accepting these terms and conditions, you acknowledge that any personal or property damage is the sole responsibility of the Host. Rent 2 Park makes no representation and warrants the liability of these services. If a user utilizes these services and releases their keys, they do so at their own risk. 
 
8. Payment Distribution and Chargebacks. All funds paid by you for the use of a Host’s property will be paid by our merchant partners, Stripe Inc. / PayPal Inc. / Apple Pay Inc. to process each payment. Host payments will be sent to host’s payment dashboard as soon as the reservation has ended. However, host’s will not be able to cash out until 24 hours to allow payment to settle in their account.  Our standard policy states that parking charges, minus Rent 2 Park fees, will automatically be distributed to the Host after 24 hours from the commencement of the Reservation. During the 24-hour period following commencement of the reservation, you will have the opportunity to contact Rent 2 Park and alert them of any issues you may have experienced leading up to or during the Reservation that you consider tantamount to a failure on the part of the Host to deliver what was promised or represented. We will adjudicate such matters at our sole discretion, and at our sole discretion may or may not elect to refund charges to your or withhold distribution of parking charges indefinitely while we investigate the matter. If we have not received a formal support ticket from you detailing your complaint and why you feel the service received was unsatisfactory within the 24-hour window, any right to receive a refund or any financial recourse in regard to that specific Reservation will expire.
 
Rent 2 Park uses Stripe Inc. / Apple Pay Inc. / PayPal Inc. for payment processing services. By using the Stripe, PayPal and Apple Pay payment processing services you agree to their Payment Services Agreement available at https://www.apple.com/legal/applepayments/direct-payments/  and https://stripe.com/legal and https://www.paypal.com/us/webapps/mpp/ua/useragreement-full 
 
Part II - Host Services
 
9. Appointment as Agent. By creating a Listing in the Services and becoming a Host, you appoint Rent 2 Park as your agent for the purposes of connecting your offered space with Drivers in need of parking services and forming binding agreements between you and Drivers using the Services. You also appoint as your agent for the collection and distribution of your rental fees and you agree to pay a fee to Rent 2 Park for every rental transaction for these services. 
 
10. Legal Right to Rent Property. Rent 2 Park provides tools and features that enable Hosts to list and rent their property for parking use. By using the Services to list an available parking space for rent, you are attesting that you are the legal owner/operator of the property being offered or have obtained the right to rent out the property. It is your responsibility to be aware of and abide by all local laws, codes, or HOA and neighborhood policies. Rent 2 Park is no way responsible for any repercussions stemming from your failure to make yourself aware of and abide by your local laws and regulations.  
 
11. Honoring of reservations, Cancellations & Penalties.  All Hosts will have the opportunity to approve or decline reservation requests from Users (whether manually at the time of request or by pre-authorizing Rent 2 Park to automatically approve all requests for the period of the time that the listing is available). Once you have approved a reservation request, you must honor the request. If you choose to cancel an approved request, you agree to be subject to the Rent 2 Park Cancellation Policy which is subject to change at Rent 2 Park’s sole discretion. You also agree that Rent 2 Park may assess penalties for failure to deliver a reserved parking space to another User. Penalties may include but are not limited to, cash fines to be paid immediately or taken from your future earnings until paid in full, account suspensions and negative reviews posted publicly on the Services in association with your account, which will inform and warn other Users of your cancellation or failure to deliver a reserved parking space. By registering your payment information with the Services, you agree to allow Rent 2 Park to automatically charge you in accordance with these policies. The fees and fines charged may vary.  
 
12. Host Service Fees. By listing your property with the Services, you agree to pay a portion of the gross parking cost to Rent 2 Park as a service fee for all completed transactions. Rent 2 Park may change its fees or fee structure at any time without notice. 
 
13. Payment Distribution and Chargebacks. All funds paid by Drivers for the use of your property will be paid directly to the host’s dashboard but will not be able to cash out until 24 hours from the satisfactory commencement of the Reservation. Our standard policy states that parking charges, minus Rent 2 Park fees, will automatically be distributed to the host and after 24 hours from the commencement of the Reservation the host will be able to withdraw funds. However, during the 24-hour period following commencement of the Reservation, the Driver will have the opportunity to contact Rent 2 Park and alert them of any issues they experienced leading up to or during the Reservation that they consider tantamount to a failure on the part of the Host to deliver what was promised or represented. We will adjudicate such matters at our sole discretion and, at our sole discretion may elect to refund all chargers to the Driver or withhold distribution of parking charges indefinitely while we investigate the matter. If we have not received a formal support ticket from you detailing your complaint and why you feel the service received was unsatisfactory within the 24-hour window, you will no longer have any right to receive a refund or any financial recourse in regard to that specific Reservation.  We may also elect to garnish or withhold future parking distributions owed you for reasons that may include but are not limited to, reimbursement of Driver chargebacks, when the chargeback was directly correlated to a Reservation carried out on your Listing, or penalty fees that we may charge for violating this set of Terms & Conditions. 
 
Rent 2 Park uses Strip, also division of PayPal, Inc. for payment processing services. By using the Stripe payment processing services you agree to the Stripe Payment Services Agreement available at https://stripe.com/legal and the applicable bank agreement/terms available at https://stripe.com/payment-terms/legal 
 
14. Usage Guidelines. As a Host you agree not to contact or attempt to contact Drivers with intent to conduct a rental transaction in relation to a property that you have listed with the Services by means other than the Services. You also agree not to use the Services to solicit or offer other User’s goods or services of any kind beyond reservation and rental of parking spaces. 
 
15. Damage to Person or Property. By consenting to this Terms & Conditions you acknowledge that when you enter into a rental agreement with a Driver you are voluntarily granting the renting party consent to enter your property or a property which you have been licensed to operate. Wherever possible Rent 2 Park will take steps to ensure that users and their property are safe from damage or harm, but by agreeing to these terms, you acknowledge that Rent 2 Park is not responsible for any damage or loss to property or person that may occur while Rent 2 Park users are on your property or engaged in a parking reservation with you. All parking transactions are entered into at your own risk. We cannot and do not guarantee in any way the security or safety of your property. It is your responsibility to ensure that your property is properly secured. If your property is damaged by another Rent 2 Park user, you agree to first attempt to resolve the matter with the user. If the matter cannot be resolved through direct contact with the user, you may contact Rent 2 Park Customer service to record your case so that we can assess the situation and offer recourse where possible and where we deem necessary. Rent 2 Park does not provide any insurance coverage to any User at any time. You are solely responsible for obtaining the required insurance coverage necessary to rent out your property for use by others.  
 
Part III – Terms for All Services
 
16. Access to the Services. At present the Services are free to access, but in order to access a majority of the features offered in the Services, you will be required to submit basic personal information.
 
17. Your Account. You are required to create an account with Rent 2 Park through the Rent 2 Park Site or Rent 2 Park Application (“Account”) in order to use the Reservation Services. You are not permitted to register or maintain more than one (1) Account. We reserve the right to suspend or delete your Accounts if we believe that you are maintaining multiple Accounts or believe you have breached this Terms & Conditions in any way. When registering for an Account, you must provide true, accurate, current and complete data about yourself on the Rent 2 Park registration form. You agree that you will not falsify any information about your identity, or impersonate another identity, or create an account with a fictitious identity. You also agree to promptly update your Account data to keep it true, accurate, current, and complete. You are solely responsible for maintaining the confidentiality of your Account and the information in your Account, and you are solely responsible for all use of your Account, whether or not authorized by you. You agree to immediately notify Rent 2 Park of any unauthorized use of your Account or any other breach of security related to your use of the Services.  Rent 2 Park will not be liable for any misuse or unauthorized access to any User’s Account. 
 
18. Communications from Rent 2 Park.  By accepting this Terms & Conditions you agree to receive communications from Rent 2 Park and the Services. The Rent 2 Park Applications may use GPS locator capabilities to identify your location at the time of use. Rent 2 Park may send you SMS text messages to provide you information regarding the Services or as otherwise described in our Rent 2 Park Privacy Policy. You hereby consent to receiving such SMS text messages and are responsible for any associated charges from your cellular provider. The communication standards for the Services include, but are not limited to: Email, SMS, in-app messaging, and web-based browser technology. In order to use the Rent 2 Park Applications, you must maintain an active account with a carrier of electronic communications through mobile devices and you may not use a prepaid cellular phone to access the Services.
 
19. User-Generated Content. The Services provide a platform for Users to create and publish content of their creation. By publishing and displaying content of any kind on the Rent 2 Park Site or through the Rent 2 Park Applications you thereby assign and transfer copyright, and all other rights to such content, to Rent 2 Park. For the avoidance of doubt, we are permitted to use any content posted by you to the Services for any of our business purposes. This right will still apply after the termination of your registration or membership. You may not use the Services for any unlawful purpose or any purpose that violates any local policies, or to publish any content that may, at Rent 2 Park’s sole discretion, be deemed offensive, inaccurate, misleading, defamatory, fraudulent, or illegal. Users are not entitled to publish any content that could be construed as an advertisement or offer for anything other than parking spaces that fall within this set of Terms & Conditions. Rent 2 Park reserves the right to remove any content from the Services at any time at our sole discretion and without notice.
 
20. Promotional Uses. By accepting these Terms & Conditions you agree to allow Rent 2 Park to use any of your quotes, photos or videos pertaining to Rent 2 Park, including images and videos of you, as part of Rent 2 Park’s media and promotional outreach.  
 
21. Complaints and Disputes Between Users. In the case of a dispute between you and another User, you agree that you will first attempt to resolve the matter through direct communication, through the Services, with the User. In the event that the dispute cannot be resolved through direct communication, you may file a support ticket and request that Rent 2 Park assist in resolving the matter. By doing so you authorize Rent 2 Park to deal with the dispute or complaint as we deem appropriate. You also authorize us to use any and all funds we, or our merchant partners, may be holding on your behalf to resolves the matter. You additionally authorize us to deduct funds from or charge any payment method which you have registered with the Services for any amount up to \$350 USD in order to resolve the matter.  
 
22. Referral programs and promotional offers. Rent 2 Park may choose to offer limited-time promotional offers or referral rewards programs. In order to be eligible for referral rewards, the Users referred by you must be brand new unregistered Users of the Services. They must also use the exact code given them by you to redeem an introductory offer or must sign up using the email or phone number with which you invited them. They must also complete a transaction as a Host or Driver before you can be eligible to receive rewards. The rewards offered may be changed by Rent 2 Park at any time without notice. All promotional offers, coupon codes, introductory offers, account credits, or rewards may be changed, revoked, denied, or canceled at any time without any notice and at Rent 2 Park’s discretion, whether already granted to the User or not yet accrued. 
 
23. Rent 2 Park Promo Code Terms and Conditions. Any Rent 2 Park promotional code or coupon in any form (the “Code”) issued by Rent 2 Park is subject to the following terms and conditions (“Promo Terms”). Your receipt and/or redemption of the Code constitute acceptance of and agreement with these Promo Terms. Other terms and conditions may apply to use of the Rent 2 Park Services. Specifically, without limitation, access to and use of the Service is subject to the Rent 2 Park Terms & Conditions.  The Code is only redeemable on the Services. A Code can be used only once and only one Code may be used per transaction. Codes are void if not obtained through authorized, legitimate channels, or if any part of the code is altered, duplicated, forged, counterfeited, or tampered with in any way or do not contain proper security devices (a “nonconforming Code”). Any attempt to obtain or generate multiple Codes and/or nonconforming Codes and/or to use multiple names, email addresses, phone numbers, and/or any fraudulent or other non-permissible means to obtain or use Codes, as determined by Rent 2 Park in its sole discretion, will give Rent 2 Park the right to void the Code and disqualify the user. The Code has no cash value, and cannot be exchanged for cash or credit, except as required by law (in which case the value of the Code is deemed \$0.001). The Code cannot be bought or sold and is void if sold or exchanged for compensation. Any unused value will be forfeited. Codes cannot be used for past purchases of Services or offers. Codes are void where prohibited by law.  If a Code is used in violation of these Terms, or if your use of the Code with the Services otherwise violates the Terms & Conditions, Rent 2 Park reserves the right to (a) cancel any transaction on the Services; (b) void the value of the Code; and/or (c) charge your credit card for the full value of the Services ordered without the Code applied.  RENT 2 PARK AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS MAKE NO WARRANTY, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO ANY CODE. YOU HEREBY RELEASE RENT 2 PARK AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS, FROM AND AGAINST ANY AND ALL LIABILITY RELATING TO THESE PROMO TERMS OR THE CODE. 
 
24. Technical Requirements.  Use of the Services requires Internet access through your computer or mobile device. You are responsible for all mobile carrier charges resulting from your use of the Services, including from any notifications provided by the Services. Rent 2 Park does not guarantee that the Services will be compatible with all devices or will be supported by all mobile carriers. You may be required to have JavaScript (or similar technologies) enabled to use the Rent 2 Park Site, and some features and portions of the Rent 2 Park Site (including, but not limited to, making, modifying, or canceling Reservations) may not be accessible with JavaScript disabled.  The user interface and functionality may not be the same across all platforms and devices. Your access to the Services may be occasionally restricted or blocked to allow for repairs, maintenance, or the introduction of new features. In these cases, we will attempt to restore access as soon as reasonably possible. Any such interruptions to the Service shall not constitute a breach of these terms by Rent 2 Park. Rent 2 Park will not be responsible for any failure or inability to make good on an agreement between and yourself and another User caused by a technical difficulty, connection or communication issue, or any interruption of the Services. 
 
25. Modifications to Services. Rent 2 Park reserves the right, in its sole discretion, to modify the Services from time to time and without any prior notice to User, including, without limitation, removing, adding, or modifying portions of the Rent 2 Park Site, Rent 2 Park Applications, and/or availability of certain Listings. Rent 2 Park shall have no liability to you for any of the foregoing actions. If you object to any such changes, your sole recourse shall be to immediately cease using the Services. Continued use of the Services following any such changes shall indicate your acknowledgment of, and consent to, such changes and satisfaction with all the Services.
 
26. Intellectual Property Rights and Grant of Rights to User. The features, information, and materials provided and depicted through the Services and on the Rent 2 Park Site and Rent 2 Park Application are protected by copyright, trademark, patent and other intellectual property laws, and are the sole property of Rent 2 Park. All text, graphical content, video, data, and other content made available through the Services (collectively, the “Rent 2 Park Content”) are provided to User by Rent 2 Park or its partners or licensors solely to support User’s permitted use of the Services. The Rent 2 Park Content may be modified from time to time by Rent 2 Park in its sole discretion and without notice to User. Except as expressly set forth herein, no license, right, or interest is granted to User for any other purpose, and any other use of the Services or the Rent 2 Park Content by User shall constitute a material breach of this Terms & Conditions. Rent 2 Park and its partners or licensors retain all rights in and to the Services, Rent 2 Park Content, and any associated patents, trademarks, copyrights, mask work rights, trade secrets, or other intellectual property rights.
 
27. Application License. Subject explicitly to the terms and conditions of this Terms & Conditions, Rent 2 Park grants User a non-exclusive, non-transferable, revocable license to use the Rent 2 Park Applications, in object code form only, on User’s compatible devices, solely to facilitate User’s permitted use of the Services.  Users grant to Rent 2 Park a perpetual, royalty free, worldwide license to any improvement to or created from, or derivative works based on the Services.
 
28. Use Restrictions. The Services and Rent 2 Park Content are offered solely for User’s personal use for the purposes described in this Terms & Conditions. Any and all other uses are prohibited. You agree not to (and not to allow any third party to): (a) use any robot, spider, scraper, or other automatic or manual device, process, or means to access the Services or copy any Rent 2 Park Content except as expressly authorized by Rent 2 Park; (b) take any action that imposes or may impose (in Rent 2 Park’s sole determination) an unreasonable or a disproportionately large load on the Services or Rent 2 Park’s infrastructure; (c) utilize any device, software, or routine that will interfere or attempt to interfere with the functionality of the Services; (d) rent, lease, copy, provide access to, or sublicense any portion of the Services or Rent 2 Park Content to a third party; (e) use any portion of the Services or Rent 2 Park Content to provide, or incorporate any portion of the Services or Rent 2 Park Content into, any product or service provided to a third party; (f) reverse engineer, decompile, disassemble, or otherwise seek to obtain the source code or non-public APIs to the Services, except to the extent expressly permitted by applicable law (and then only with advance notice to Rent 2 Park); (g) modify any Services or Rent 2 Park Content or create any derivative product from any of the foregoing; (h) remove or obscure any proprietary or other notices contained in the Services or Rent 2 Park Content; (i) use the Services or Rent 2 Park Content for any illegal purpose; or (j) publicly disseminate information regarding the performance of the Services or Rent 2 Park Content or access or use the Services or Rent 2 Park Content for competitive analysis or benchmarking purposes.
 
29. Do Not Use While Driving.  You agree, represent, and warrant, so long as you use or access the Services YOU WILL NOT, UNDER ANY CIRCUMSTANCES, ACCESS, VIEW, OR USE THE SERVICES WHILE DRIVING OR OTHERWISE OPERATING A VEHICLE OF ANY KIND (including, without limitation, a car, truck, motorcycle, motor scooter, or bicycle) or operating any dangerous equipment or machinery. You understand that using any handheld device in these circumstances is extremely dangerous, and can result in property damage, physical injuries (including dismemberment), or death. You further agree, represent and warrant, that you will not use or access the Services in any manner that places yourself or any other person at risk of injury, and that you will abide by all traffic laws. While effort is made to assure the accuracy of the information presented to the User, the User is solely responsible for safe driving and for the consequences of decisions as to where to travel, drive, or park. Under no circumstance will any of the Rent 2 Park Parties (as defined below) assume any responsibility or liability for the consequences of driving decisions made by Users. You agree that no Rent 2 Park Party shall be liable for any driving decisions made by you or at your suggestion, or for any damages, injury, or other harm caused by your use of or accessing the Services or Rent 2 Park Content while driving, operating equipment or machinery, or otherwise in a dangerous and unsuitable manner, and you hereby waive any claims or causes of action you may have, now or in the future, arising from or relating to the same. IN THE EVENT THAT ANY PARTY NAMES ANY RENT 2 PARK PARTY AS A DEFENDANT IN A CASE INVOLVING YOUR USE OF THE SERVICES WHILE OPERATING A VEHICLE, YOU AGREE TO INDEMNIFY AND HOLD ANY SUCH RENT 2 PARK PARTY HARMLESS IN SUCH ACTION.
 
30. Government End Users. The Services constitute a “commercial item” as defined at 48 C.F.R. 2.101, consisting of “commercial computer software” and “commercial computer software documentation” as such terms are used in 48 C.F.R. 12.212. Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7202-4, all U.S. Government end users of any the Services are licensed only as commercial items and with only those rights that are granted to all other Users pursuant to this Terms & Conditions.
 
31. Export Control. You may not use, export, or re-export any of the Rent 2 Park Applications, Rent 2 Park Content, or other aspects of the Services (or any copy or adaptation of the foregoing) in violation of applicable law, including, without limitation, United States and foreign export laws and regulations. You represent and warrant that you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a “terrorist supporting” country and that you are not listed on any U.S. Government list of prohibited or restricted parties.
 
32. Termination.  Rent 2 Park may suspend your ability to use all or any element of the Services or may terminate this Terms & Conditions effective immediately, without any notice or explanation. Without limiting the foregoing, Rent 2 Park may suspend your access to the Services if we believe you to be in violation of any part of this Terms & Conditions (including any associated Rent 2 Park Policies). After any suspension or termination, you may or may not be granted permission to re-establish an Account, and you may lose access to and be unable to use any points accumulated towards any rewards program (if any) in effect at the time. You agree that Rent 2 Park shall not be liable to you for any termination of this Terms & Conditions or for any effects of any termination of this Terms & Conditions. You are always free to discontinue your use of the Services at any time. You understand that any termination of your Account may involve deletion of any content you stored in your Account for which Rent 2 Park will have no liability whatsoever.
 
33. Reviews, Comments, Communications and Other Content. We appreciate hearing from you.  The Services may permit you to submit reviews, comments, and ratings; send emails and other communications; and submit suggestions, ideas, comments, questions, or other information for publication and distribution to Users and other third parties (“User Content”).  You are solely responsible for all User Content you generate (and for your Account generally).  Any such User Content must not be illegal, malicious, threatening, obscene, racist, defamatory, libelous, pornographic, infringing of intellectual property rights, promoting of illegal activity or harm to groups and/or individuals, invasive of privacy, false, inaccurate, or otherwise injurious to third parties (including, but not limited to, any content that is copyrighted or subject to third party proprietary rights, including privacy, publicity, trade secret, etc., unless you are the owner of such rights or have the appropriate permission for their rightful owner to specifically submit such content), or otherwise objectionable, and must not consist of or contain software, computer viruses, commercial solicitation, political campaigning, chain letters, mass mailings, any form of “spam” or references to illegal activity, malpractice, purposeful overcharging, false advertising, or health code violations (e.g., foreign objects in food, food poisoning, etc.). You may not use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of User Content. Rent 2 Park reserves the right (but has no obligation) to monitor, remove, or edit User Content in Rent 2 Park’s sole discretion, including if the User Content violates this Terms & Conditions (including any associated Rent 2 Park Policies), but you acknowledge that Rent 2 Park may not regularly review submitted User Content. If you do submit User Content, please be aware that unless we indicate otherwise, you grant Rent 2 Park a nonexclusive, perpetual, royalty-free, irrevocable, and fully transferable right to use, modify, reproduce, adapt, translate, publish, create derivative works from, distribute, display, and otherwise exploit such content throughout the world in any media. Rent 2 Park takes no responsibility and assumes no liability for any User Content submitted by you or any other User or third party.  
 
You agree to indemnify and hold any Rent 2 Park Party harmless in the event Rent 2 Park is named as a defendant in an action related to your User Content and you hereby affirm that we have the right to determine whether any of your User Content submissions are appropriate and comply with this Terms & Conditions, to remove any and/or all of your submissions, and to terminate your Account with or without prior notice.  You understand and agree that any liability, loss, or damage that occurs as a result of any of the use of any User Content that you make available or access through your use of the Services is solely your responsibility.  Rent 2 Park is not responsible for any public display or misuse of any User Content.  Rent 2 Park does not, and cannot, pre-screen or monitor all User Content; however, at our discretion, we, or technology or agents we employ, may monitor and/or record your interactions with the Services and your submission(s) of User Content.
 
34. Your Representations and Indemnity.  You represent and warrant that you own or otherwise control all of the rights to any User Content submitted by you; that all User Content submitted by you is accurate; and that exploitation of such User Content by Rent 2 Park and its other Users, partners, and licensees will not violate this Terms & Conditions, cause injury to any person or entity, or infringe any third-party rights (including, without limitation, intellectual property rights and rights of privacy or publicity). You will indemnify, hold harmless, and (at Rent 2 Park’s request) defend Rent 2 Park, its affiliates, and its and their representatives, agents, directors, managers, officers, employees, and shareholders (collectively, the “Rent 2 Park Parties”) from and against all claims resulting from (a) any User Content submitted by you, (b) your use of the Services or (c) any breach or alleged breach by you of this Terms & Conditions.
 
35. Liability Limitations. TO THE MAXIMUM EXTENT PERMITTED BY LAW, EXCEPT AS EXPRESSLY SPECIFIED BELOW WITH RESPECT TO RENT 2 PARK GIFT CARDS AND MERCHANT GIFT CARDS, IN NO EVENT SHALL THE RENT 2 PARK PARTIES BE LIABLE FOR ANY INJURIES, LOSSES, CLAIMS, OR DIRECT DAMAGES OR ANY SPECIAL, EXEMPLARY, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, WHETHER BASED IN CONTRACT, TORT, OR OTHERWISE, AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, WHICH ARISE OUT OF OR ARE ANY WAY CONNECTED WITH (A) THIS TERMS & CONDITIONS; (B) ANY USE OF THE SERVICES, THE RENT 2 PARK CONTENT OR THE USER CONTENT; (C) ANY FAILURE OR DELAY (INCLUDING, BUT NOT LIMITED TO, THE USE OR INABILITY TO USE ANY COMPONENT OF THE RESERVATION SERVICES); OR (D) YOUR VISIT TO ANY PARKING LOCATION OR THE PERFORMANCE, NON-PERFORMANCE, CONDUCT, OR POLICIES OF ANY HOLDER OR MERCHANT IN CONNECTION WITH THE SERVICES. IN ADDITION, YOU SPECIFICALLY UNDERSTAND AND AGREE THAT ANY THIRD PARTY DIRECTING YOU TO THE RENT 2 PARK SITE OR PACEMINT APPLICATIONS BY REFERRAL, LINK, OR ANY OTHER MEANS IS NOT LIABLE TO USER FOR ANY REASON WHATSOEVER, INCLUDING, BUT NOT LIMITED TO, DAMAGES OR LOSS ASSOCIATED WITH THE USE OF THE SERVICES OR THE RENT 2 PARK CONTENT. RENT 2 PARK IS NEITHER AN AGENT OF NOR OTHERWISE ASSOCIATED WITH ANY HOST FOR WHICH A USER HAS MADE A RESERVATION OR UTILIZES ANY COUPON.
 
You and Rent 2 Park understand and agree that the disclaimers, exclusions, and limitations in this Section 19 and in Section 20 below are essential elements of this Terms & Conditions, and that they represent a reasonable allocation of risk. In particular, you understand that Rent 2 Park would be unable to make the Services available to you except on these terms and hereby agree that this Terms & Conditions will survive and apply even if any limited remedy specified in this Terms & Conditions is found to have failed its essential purpose.
 
36. Disclaimer of Warranties. THE SERVICES, ALL RENT 2 PARK CONTENT, AND ANY OTHER INFORMATION, PRODUCTS, AND MATERIALS CONTAINED IN OR ACCESSED THROUGH THE SERVICES, ARE PROVIDED TO USER ON AN “AS IS” BASIS AND WITHOUT WARRANTY OF ANY KIND. RENT 2 PARK EXPRESSLY DISCLAIMS ALL REPRESENTATIONS, WARRANTIES, CONDITIONS, OR INDEMNITIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NON-INFRINGEMENT, OR ANY WARRANTY ARISING FROM A COURSE OF DEALING, PERFORMANCE OR TRADE USAGE. RENT 2 PARK DOES NOT WARRANT THAT YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT RENT 2 PARK WILL REVIEW THE INFORMATION OR MATERIALS MADE AVAILABLE THROUGH THE SERVICES FOR ACCURACY, THAT IT WILL PRESERVE OR MAINTAIN ANY SUCH INFORMATION OR MATERIALS WITHOUT LOSS, OR THAT RENT 2 PARK WILL REVIEW AND POLICE THE USER CONTENT. RENT 2 PARK SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, VIRUSES CONTAINED IN ANY USER CONTENT, THE RENT 2 PARK SITE, RENT 2 PARK APPLICATION OR ANY RENT 2 PARK COMMUNICATION, SERVICE FAILURES OR OTHER PROBLEMS INHERENT IN USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS OR OTHER SYSTEMS OUTSIDE THE REASONABLE CONTROL OF RENT 2 PARK.
 
THE FOREGOING DISCLAIMERS APPLY TO THE MAXIMUM EXTENT PERMITTED BY LAW. YOU MAY HAVE OTHER STATUTORY RIGHTS. HOWEVER, THE DURATION OF STATUTORILY REQUIRED WARRANTIES, IF ANY, SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
 
37. Links to/from Third-Party Websites. The Services may contain hypertext links to/from websites operated by parties other than Rent 2 Park. Such hypertext links are provided for User’s reference only, and Rent 2 Park does not control such websites and is not responsible for their content.  Neither these third party sites, nor any of the contents thereof or promotions, materials, information, or goods or services available thereon, are in any way investigated, monitored, or checked for accuracy, appropriateness or completeness by Rent 2 Park.  Rent 2 Park’s inclusion of any hypertext links to/from such websites does not imply any endorsement of the material on such websites or any association with their operators. Rent 2 Park assumes no liability whatsoever for any such third-party websites or any content, features, products, or services made available through such third-party websites.  If you decide to leave the Rent 2 Park Site or Application, as applicable, and access any such third party sites or to use or install any third-party applications, software or content, you do so at your own risk and you should be aware that our terms and policies no longer govern.  You should review the applicable terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Rent 2 Park Site (or Rent 2 Park Application) or relating to any applications you use or install from any such site.
 
38. Release.  Hosts are solely responsible for their interactions with you and any and all claims, injuries, illnesses, damages, liabilities and costs (“Claims”) suffered by you or any third party as a result of your interaction with or visit to any Host. YOU HEREBY RELEASE THE RENT 2 PARK PARTIES FROM ANY AND ALL SUCH CLAIMS. IN CONNECTION WITH THE FOREGOING, YOU HEREBY WAIVE ANY CIVIL CODE WHICH STATES DIRECTLY OR INDIRECTLY: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.” You hereby expressly waive and relinquish all rights and benefits under this section and any law of any jurisdiction of similar effect with respect to the release of any unknown or unsuspected claims you may have against the Rent 2 Park Parties pertaining to the subject matter of this Section 36.
 
39. Notify Us of Infringers.  We will respond to allegations of copyright violations in accordance with the Digital Millennium Copyright Act (“DMCA”). In response to a valid notice (as described below) we will remove any allegedly infringing content from the Services and will take reasonable steps to contact the provider of the removed content so that a counter-notification may be filed. Upon receipt of a valid counter-notification, we will evaluate the counter-notification and determine whether to restore the content in question, unless we receive notice from the notification provider that a legal action has been filed seeking a court order to restrain the alleged infringer from engaging in the infringing activity.  If you believe any of the Services violate your copyright, notify our copyright agent in writing.  The contact information for our copyright agent is at the bottom of this section.
 
Copyright infringement notices must:  (a) provide your physical or electronic signature; (b) identify the copyrighted work that you believe is being infringed; (c) identify the item that you think is infringing your work and include sufficient information about where the material is located so that we can find it; (d) provide us with a way to contact you, such as your address, telephone number, or email; (e) provide a statement that you believe in good faith that the item you have identified as infringing is not authorized by the copyright owner, its agent, or the law to be used on the Services; (f) provide a statement that the information you provide in your notice is accurate, and that (under penalty of perjury) you are authorized to act on behalf of the copyright owner whose work is being infringed; and (g) be sent to Rent 2 Park’s copyright agent at the following address:
 
Rent 2 Park, INC - Copyright Enforcement
7860 W Commercial Blvd, 800
Lauderhill, FL 33351
954-406-0283
Info@Ren2Park.com
 
40. Severability. If any part of this Terms & Conditions is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and Agreement shall continue in effect
 
41. Assignment. This Terms & Conditions, and the rights granted, and obligations undertaken hereunder, may not be transferred, assigned or delegated in any manner by a User, but may be freely transferred, assigned, or delegated by Rent 2 Park.
 
42. Waiver. Any waiver of any provision of this Terms & Conditions, or a delay by any party in the enforcement of any right hereunder, shall neither be construed as a continuing waiver nor create an expectation of non-enforcement of that or any other provision or right.
 
43. Arbitration and Venue.  Any and all controversies, disputes, demands, counts, claims, or causes of action (including the interpretation and scope of this clause) between you and the Rent 2 Park Parties or their successors or assigns shall exclusively be settled through binding and confidential arbitration in Broward County, Florida.
 
Arbitration shall be subject to the Federal Arbitration Act and not any state arbitration law. The arbitration shall be conducted before one commercial arbitrator, certified by the American Arbitration Association (“AAA”), with substantial experience in resolving commercial contract disputes. As modified by this Terms & Conditions, and unless otherwise agreed upon by the parties in writing, the arbitration will be governed by the AAA’s Commercial Arbitration Rules and, if the arbitrator deems them applicable, the Supplementary Procedures for Consumer Related Disputes (collectively, the “Rules and Procedures”).
 
You and Rent 2 Park must abide by the following rules: (a) ANY CLAIMS BROUGHT BY YOU OR RENT 2 PARK MUST BE BROUGHT IN THE PARTY'S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING; (b) THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS, MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING, AND MAY NOT AWARD CLASS-WIDE RELIEF; (c) the arbitrator shall honor claims of privilege and privacy recognized at law; (d) the arbitration shall be confidential, and neither you nor we may disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcement of the arbitration award; (e) the arbitrator may award any individual relief or individual remedies that are permitted by applicable law; and (f) each side pays its own attorneys’ fees and expenses unless there is a statutory provision that requires the prevailing party to be paid its fees and litigation expenses, and, in such instance, the fees and costs awarded shall be determined by the applicable law.
 
Notwithstanding the foregoing, either you or Rent 2 Park may bring an individual action in small claims court. Further, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark, or trade secret shall not be subject to this arbitration agreement. Such claims shall be exclusively brought in the state or federal courts located in Broward County, Florida. Additionally, notwithstanding this agreement to arbitrate, either party may seek emergency equitable relief before the state or federal courts located in Broward County, Florida in order to maintain the status quo pending arbitration, and hereby agree to submit to the exclusive personal jurisdiction of the courts located within Broward County, Florida for such purpose. A request for interim measures shall not be deemed a waiver of the right to arbitrate.
 
With the exception of subparts (a) and (b) in this Section (prohibiting arbitration on a class or collective basis), if any part of this arbitration provision is deemed to be invalid, unenforceable or illegal, or otherwise conflicts with the Rules and Procedures, then the balance of this arbitration provision shall remain in effect and shall be construed in accordance with its terms as if the invalid, unenforceable, illegal or conflicting part was not contained herein. If, however, either subpart (a) or (b) is found to be invalid, unenforceable or illegal, then the entirety of this arbitration provision shall be null and void, and neither you nor Rent 2 Park shall be entitled to arbitration. If for any reason a claim proceeds in court rather than in arbitration, the dispute shall be exclusively brought in state or federal court located in Broward County, Florida.
 
For more information on AAA, the Rules and Procedures, or the process for filing an arbitration claim, you may call AAA at 800-778-7879 or visit the AAA website at http://www.adr.org 
 
44. Choice of Law. The Services are operated by a U.S. entity, and this Terms & Conditions is made under and shall be governed by and construed in accordance with the laws of the State of Florida, consistent with the Federal Arbitration Act, without giving effect to any principles that provide for the application of the law of another jurisdiction.
 
45. General Terms.  You agree that no joint venture, partnership, or employment relationship exists between you and any of the Rent 2 Park Parties as a result of agreeing to this Terms & Conditions or use of the Services. Further, no joint venture, partnership, or employment relationship exists between any of the Rent 2 Park Parties and any Host. Our performance of this Terms & Conditions is subject to existing laws and legal process, and nothing contained in this Terms & Conditions limits our right to comply with law enforcement or other governmental or legal requests or requirements relating to your use of the Services or information provided to or gathered by us with respect to such use.  A printed version of this Terms & Conditions and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Terms & Conditions to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.  Fictitious names of companies, products, people, characters, and/or data mentioned within the Services are not intended to represent any real individual, company, product, or event.  Any rights not expressly granted herein are expressly reserved.
 
46. ACKNOWLEDGEMENT. BY USING THE SERVICE OR ACCESSING THE RENT 2 PARK SITE OR APPLICATION, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM.
 
47. Entire Agreement.  Notwithstanding any agreements or terms expressly incorporated by reference in this Terms & Conditions, this Terms & Conditions constitutes the entire agreement between the parties.  This Terms & Conditions (as it may from time to time be amended, restated, or otherwise modified) supersedes any prior agreements, understandings, or negotiations, whether written or oral.  
 
REVISION DATE: September 1st, 20121
                ''',
                    style: TextStyle(color: Constants.COLOR_ON_SURFACE, fontSize: 14, fontFamily: Constants.GILROY_REGULAR))),
            const SizedBox(height: 10),
            const Padding(
                padding: EdgeInsets.symmetric(horizontal: 15, vertical: 20),
                child: Text(AppText.PRIVACY_POLICY,
                    style: TextStyle(color: Constants.COLOR_ON_SURFACE, fontSize: 18, fontFamily: Constants.GILROY_BOLD))),
            const Padding(
                padding: EdgeInsets.symmetric(horizontal: 20),
                child: Text('''
Effective: September 1st, 2021 

Rent 2 Park, INC. (“Rent 2 Park,” “we,” “us”) takes your privacy very seriously. We provide this Privacy Policy to inform you of our policies and procedures regarding the collection, use and disclosure of personal information we receive from Users of our website at Rent 2 Park.com (the “Site”) and the Rent 2 Park iOS mobile device application (the “App”) or any other products provided by Rent 2 Park, INC. The Site, App, and all other Rent 2 Park services are collectively referred to as the “Services.” This Privacy Policy applies only to information that you provide to us through use of the Services or by direct contact with a representative of Rent 2 Park. By using the Services, you are agreeing to be bound by these policies. Our privacy policy will be updated as necessary. We will notify you of any material changes and all updates to the privacy policy will be posted on the Site and within the Mobile App. 

Key Terms 

Services: The website at Rent 2 Park.com (the “Site”) and the Rent 2 Park iOS mobile device application (the “App”) or any other products provided by Rent 2 Park, INC. The Site, App, and all other Rent 2 Park services are collectively referred to as the “Services.”  

“User”: Any individual who is in contact with the Services, whether registered or not. 

“Registered User”: Any individual who has contacted the Services, provided the required information, and completed the steps necessary to create an account. 

“Host”: Any Registered User who has created and published a Listing in the Services whether the owner, renter, or employee of the owner of that property.  

“Guest”: Any Registered User who uses the Services to seek a parking space, request to utilize a parking space, or complete an exchange of funds with a Host for use of property.  

“Listing”: A property which has been input into the Services and offered by a Host for a Guest to utilize.  

1. The PII We Collect.  

In the course of using the Services, you may provide us with “Personally Identifiable Information.” This refers to information about you that can be used to contact or identify you, and information on your use of, and activities through, our Services that may be connected with you (“PII”). PII that we collect may include, but is not limited to, your first and last name, password, mobile number, email address, billing information, vehicle information including license plate number, details regarding any transaction you make or action you take using the Services, and information voluntarily given to us by you. PII may also include information you supply to us concerning your location, preferences, and interests expressed in the course of use of the Services. It is not compulsory that you provide any of the above information; however, if you choose not to, you will not be able to register as a User of the Services and will not have access to certain information and features or capability to conduct any transactions with other Rent 2 Park Users.  

1. Log Data. Our servers automatically record information about how Users (both account holders and non-account holders) use our Services. This information, referred to as “Log Data,” may include, but is not limited to, your computer’s Internet Protocol address, browser type, operating system, the web page you were visiting before you accessed our Services, the pages or features of our Services that you browsed and the time spent on those pages or features, search terms, the links on our Services that you clicked, and statistics related to your use of the Services. We use Log Data to administer the Services and to analyze (or have third parties analyze) the Log Data to improve, customize, and enhance our Services by expanding their features and functionality and tailoring them to our Users’ needs and preferences. 

2. Cookies. Like many websites, we also use automated data collection tools such as “cookies” and “web beacons” to collect certain information. “Cookies” are small text files that we transfer to your computer’s hard disk for record-keeping purposes. We use “persistent cookies” to save your registration ID and login password for future logins to the Site; and we use “session ID cookies” to enable certain features of the Site, to better understand how you interact with the Site and to monitor aggregate usage and web traffic routing on the Site. You can instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all portions of the Site or all functionality of our Services. Note that this Privacy Policy covers only our use of cookies and does not include use of cookies by third parties.  

3. Third Parties. We may also allow third parties, including, but not limited to Google Analytics, to place cookies on the Site. Third parties use these technologies to help us analyze how you use the Site and to market and advertise to you on the Site and third-party websites. These cookies also help us detect or prevent fraud or conduct risk assessments, or to collect information about your activities on the Site. To prevent Google Analytics from using your information for analytics, you may install the Google Analytics Opt-Out Browser. To opt out of Google Analytics for display advertising or customize Google display network ads, you can visit the Google Ads Settings page. We do not control any of these opt-out links and are not responsible for the availability or accuracy of these mechanisms.  

4. Web Beacons. “Web Beacons” (also known as clear gifs) are tiny graphics with a unique identifier that may be included on our Services for several purposes, including to deliver or communicate with cookies, to track and measure the performance of our Services, to monitor how many visitors view our Services, and to monitor the effectiveness of our advertising. Unlike cookies, which are stored on the User’s hard drive, web beacons are typically embedded invisibly on web pages (or in an email). 

5. Location Information. When you use the Services, we may collect and store information about your location by converting your IP address into a geographic location, or by accessing your device’s GPS coordinates or course location if you enable location services on your device. We may use location information to improve and personalize our Services for you. You may opt to not allow us to use your device’s location but doing so may prevent you from being able to use some or all of features provided by the Services. 

6. Financial Information. Rent 2 Park uses Plaid Technologies, Inc. (“Plaid”) to gather End User’s data from financial institutions. By using our service, you grant Rent 2 Park and Plaid the right, power, and authority to act on your behalf to access and transmit your personal and financial information from the relevant financial institution. You agree to your personal and financial information being transferred, stored, and processed by Plaid in accordance with the Plaid Privacy Policy. As a Registered User of the Services, you may be also asked to enter billing information in the form of a Venmo account, Apple Pay account, credit or debit card, or other payment method (Payment Info) in order to transact with other Users. You may also be asked to connect your Venmo or bank account in order to receive payment for use of your parking space (Payout Info). You are not required to enter any financial information at any time, but you will not have the ability to transact with other Users or collect funds owed to you until you have input the financial information requisite to the task you are attempting to perform. We will inform you when further financial information or other data points are required and request that you provide the data at that time. We do not store your credit/debit card info or bank account information on our servers. You consent to the transfer, collection and storage of all bank account information, credit/debit information, Payment Information and Payout Information to and by our payment processor partner, Braintree, for payment transaction purposes. Further information about measures taken by Braintree to keep your information safe and secure can be found via their website. 

7. Vehicle Data. In order to reserve a parking space on your behalf and facilitate transactions between Guests and Hosts, we will request data regarding your vehicle, including make, model, color, year, and license plate number. Your license plate number will not be made publicly visible by us. 

8. Listing Data. In order to become a Host, you will be required to create a Listing. In order to create and publish a Listing, you will be required input information specific to the Listing including but not limited to address, property type, business name, business type, property features, and hours of operation.  

9. User Ratings. The Services provides a means for other Registered Users to rate your performance and behavior as a Host or Guest. We will aggregate and store this information.  

10. How We Use PII. PII is used for the following purposes: (a) to provide and improve our Services, features and content; (b) to administer your account and your use of our Services; (c) to enable Users to enjoy and easily navigate the Site and Mobile Application; (d) to better understand your needs and interests; (e) to fulfill requests you may make; (f) to personalize your experience; (g) to provide or offer software updates and product announcements; and (h) to provide you with further information and offers from us or our partners, and to market, advertise, and inform you about products and services that we may deem relevant to you. These may include products and services offered directly by us or any entity with which we have formed a business relationship. This information and these communications may come to you in the form of email, mobile messaging, telephone contact, or direct mail depending upon the preferences which you indicate to us within your account.  

If you decide at any time that you no longer wish to receive such communications, please follow the instructions provided in any of the communications or update your “User Settings” information. (See “Changing or Deleting Information,” below.) We use information we obtain by technical means (such as the automatic recording performed by our servers or through the use of cookies) for the above purposes, and in order to monitor and analyze use of the Services for behavioral information and for technical administration of the Services, as well as to increase the functionality and user-friendliness of the Services, to better tailor the Services to your needs, to generate and derive useful data and information concerning the interests, characteristic, website and Mobile App use behavior of our Users, and to verify that visitors to the Services meet the criteria required to process their requests. 

We have the capability to re-utilize your payment information after you have completed a transaction using the Services for items such as recurring reservations, cancellation fees, and penalty fees as covered in our Terms of Services and Cancellation Policy. These policies are in place to ensure that the Services perform adequately and maintain their value for all Users. 

2. Information Sharing and Disclosure.  

1. Information We Disclose with Your Consent or at Your Request. We will display portions of your PII in your profile page and elsewhere throughout the Services according to the preferences you set in your account. Any information you choose to provide should reflect how much you want all other Rent 2 Park Users to know about you. We will share your PII with third-party sites or platforms, such as social networking sites, if you have requested that we do so. 

2. Information Shared to Facilitate Transactions on Your Behalf. When you utilize the Services to request a parking reservation with a Host, or when you publish your Listing in order to begin accepting reservations, we will share specific data points and PII about you or you’re Listing with the specific Hosts that you have requested a reservation with or with any Guest who searches for available parking in the area of your Listing. Data shared with other Users may include but is not limited to past User ratings, Listing address, features, and hours, vehicle, make, model, year, and color. Your financial information will not be shared with or made visible to other Users. Your license plate number will not be made visible but may be used as a blind verification tool. (Example: Host sees your car on his/her property and wants to verify that you are a Guest with an approved reservation. The Host may enter your plate number and the Services will compare their entry to your plate number and inform them whether it is a match or not.) 

3. Information Shared with Services Providers and Analysts. We may engage third-party service providers to work with us to administer and provide the Services. These third-party service providers may have access to your PII only for the purpose of performing services on our behalf and are expressly obligated by agreement, statute and/or applicable regulations not to disclose or use your PII for any other purpose. We may share aggregated information and non-identifying information with third parties for purposes that include, but are not limited to, industry research and analysis, demographic profiling, and other similar purposes. 

4. Information Disclosed in Connection with Business Transactions Information that we collect from our Users, including PII, is considered to be a business asset. As a result, if we go out of business, enter bankruptcy, or are acquired as a result of a transaction such as a merger, acquisition, or asset sale, your PII may be disclosed or transferred to the third-party acquirer in connection with the transaction. In such an event we will take the steps we deem appropriate to ensure that your privacy rights remain protected. 

5. Information Disclosed to Protect Us and Others. We cooperate with government and law enforcement officials or private parties to enforce and comply with the law. We may disclose any information about you to government or law enforcement officials, or private parties as we, at our sole discretion, believe necessary or appropriate to: (a) respond to claims, or legal process (including subpoenas); (b) protect our property, rights and safety, and the property, rights and safety of a third party or the public in general; and (c) stop any activity that we consider illegal, unethical, or legally actionable. 

3. Changing or Deleting Your Information. 

All Registered Users may review, update, correct, or delete the PII provided in their registration or account profile by contacting us at Hello@Rent2Park.com or by changing their User profile information. If you completely delete all such information, then your account may become deactivated. 

4. Security. 

We take reasonable administrative, physical, and electronic measures designed to protect the information that we collect from or about you (including your PII) from unauthorized access, use or disclosure. Please be aware, however, that no method of transmitting information over the Internet or storing information is completely secure. Accordingly, we cannot guarantee the absolute security of any information. By agreeing to our Terms of Services, you agree to indemnify and hold Rent 2 Park and any affiliated entities harmless, in the event that your PII is accessed by an unauthorized party as a result of using the Services. 

5. Our Policy Regarding Children. 

The Services are not directed to children under the age of 18. We do not knowingly collect personally identifiable information from children under the age of 18. If a parent or guardian becomes aware that his or her child has provided us with PII without their consent, he or she should contact us at Hello@Rent2Park.com. If we become aware that a child under 18 has provided us with PII, we will delete such information from our files. 

6. Contacting Us. 

If you have any questions about this Privacy Policy, please contact us at Hello@Rent2Park.com or 3510 Mt Vernon Houston TX 77006. 

© Rent 2 Park, INC 2021 
                ''',
                    style: TextStyle(color: Constants.COLOR_ON_SURFACE, fontSize: 14, fontFamily: Constants.GILROY_REGULAR))),
            const SizedBox(height: 10)
          ],
        ),
      ),
    );
  }
}
